webtalk_init -webtalk_dir C:/Users/biagi/3_Riconoscitore_di_sequenze/3_Riconoscitore_di_sequenze.sim/sim_1/behav/xsim/xsim.dir/riconoscitore_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 28 16:14:46 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1c4a051f-82a9-448a-ac05-974152935221" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6f5a973c404945da8de72b62fd5df0a5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "98" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8156_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1677389900 -regid "" -xml C:/Users/biagi/3_Riconoscitore_di_sequenze/3_Riconoscitore_di_sequenze.sim/sim_1/behav/xsim/xsim.dir/riconoscitore_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/biagi/3_Riconoscitore_di_sequenze/3_Riconoscitore_di_sequenze.sim/sim_1/behav/xsim/xsim.dir/riconoscitore_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/biagi/3_Riconoscitore_di_sequenze/3_Riconoscitore_di_sequenze.sim/sim_1/behav/xsim/xsim.dir/riconoscitore_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
