@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Jan 29 21:53:24 +0100 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 8a3c468bd63543ed8ed0e1db113622b3 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot digits_conv_tb_behav xil_defaultlib.digits_conv_tb -log elaborate.log"
call xelab  -wto 8a3c468bd63543ed8ed0e1db113622b3 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot digits_conv_tb_behav xil_defaultlib.digits_conv_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
