# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param synth.incrementalSynthesisCache C:/Users/Donato/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-19144-LAPTOP-KP9RFQ43/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.cache/wt [current_project]
set_property parent.project_path C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/adder.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/imports/display_7seg/anodes_manager.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/base_dei_tempi.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/imports/components/button_debouncer.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/imports/display_7seg/cathodes_manager.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/imports/display_7seg/clock_filter.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/imports/components/counter.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/decoder.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/imports/display_7seg/digits_splitter.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/imports/display_7seg/display_7seg_manager.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/handshake_system.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/imports/components/memory.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/mux_2_1.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/nodoA.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/nodoA_CU.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/nodoA_datapath.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/imports/components/register_pp.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/nodoB_datapath.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/nodoB_CU.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/nodoB.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/imports/components/rom.vhd
  C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/sources_1/new/handshake_system_on_board.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/constrs_1/imports/vivado_projects/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files C:/Users/Donato/Desktop/vivado_projects/7_Handshake/7_Handshake.srcs/constrs_1/imports/vivado_projects/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top handshake_system_on_board -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef handshake_system_on_board.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file handshake_system_on_board_utilization_synth.rpt -pb handshake_system_on_board_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
