@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sat Dec 09 17:52:15 +0100 2023
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 5b80e9d7ee714d1fb94ad520c39c5070 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot shift_register_strutturale_tb_behav xil_defaultlib.shift_register_strutturale_tb -log elaborate.log"
call xelab  -wto 5b80e9d7ee714d1fb94ad520c39c5070 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot shift_register_strutturale_tb_behav xil_defaultlib.shift_register_strutturale_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
